wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.19.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1748676505
    t:
      1:
      - 1
      - 55
      3:
      - 4
      - 16
      - 23
      - 42
      - 55
      4: 3.12.3
      5: 0.19.11
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.0005
architecture:
  desc: null
  value: MiniKL Decoder
dataset:
  desc: null
  value: books
epochs:
  desc: null
  value: 3
batch_size:
  desc: null
  value: 72
